spring:
  application:
    name: Subscriber
  data:
    mongodb:
      host: "192.168.50.10"
      port: 27017
      database: "foo_bar"
      username: "foo_bar"
      password: "FOOBAR"
      authentication-database: "foo_bar"

mqtt:
  url: "tcp://192.168.50.10:1883"
  username: "foo_bar"
  password: "FOOBAR"
  clientId: "spring-mqtt-subscriber-dev"
  topic: "home/#"